# Example configuration file

[settings]
nSteps = 200   # number of time steps
tStart = 0.5      # start time
tEnd   = 1.0     # end time

[geometry]
meshName = "src/Simulation/data/bay.msh"
borders = [
  [0.0, 0.45],    # x1, y1
  [0.0, 0.2]      # x2, y2
]                 # define where fish are located



[IO]
logName         = "file1_log"                # name of the log file created
writeFrequency  = 10
restartFile     = "result_folder/file1"   # Restart file must be provided if start time is provided.
